"""Every file the dashboard reads or writes, in one place.

The scripts live in PROJECT_DIR; everything they generate goes into one of
four subfolders beside them, so the project root stays just code:

    dashboard-project-files\\
        *.py                    the scripts
        fonts\\                  Inter + Fraunces (optional)
        cache\\                  cache.json, calendar_sync_status.json
        data\\                   todo.json, habits.json, rough_notes.txt
        secrets\\                calendar_url.txt, OAuth credentials + tokens
        logs\\                   calendar_sync.log, dashboard_crash.log

`.git`, `.gitignore` and `__pycache__` have to stay where they are — git and
Python decide those, not us.

PROJECT_DIR can be pointed somewhere else with DASHBOARD_DATA_DIR (and the
Doom notes with DASHBOARD_NOTES_DIR), which is how the stores get exercised on
a non-Windows machine and in the tests.
"""

import os
import shutil
import time
from pathlib import Path

PROJECT_DIR = Path(os.environ.get(
    "DASHBOARD_DATA_DIR", r"C:\Users\joey\dashboard-project-files"))
DOOMNOTES_DIR = Path(os.environ.get(
    "DASHBOARD_NOTES_DIR", r"C:\Users\joey\doomnotes"))

# Kept as an alias: plenty of code and habit still says DATA_DIR for the root.
DATA_DIR = PROJECT_DIR

CACHE_DIR = PROJECT_DIR / "cache"        # generated, safe to delete
USER_DATA_DIR = PROJECT_DIR / "data"     # your actual content
SECRETS_DIR = PROJECT_DIR / "secrets"    # never commit
LOGS_DIR = PROJECT_DIR / "logs"

MANAGED_DIRS = (CACHE_DIR, USER_DATA_DIR, SECRETS_DIR, LOGS_DIR)

# ── cache/ — generated by the collector and the sync, disposable ─────
CACHE_PATH = CACHE_DIR / "cache.json"
SYNC_STATUS_PATH = CACHE_DIR / "calendar_sync_status.json"

# ── data/ — written by the widget, this is the content worth keeping ─
TODO_PATH = USER_DATA_DIR / "todo.json"
HABITS_PATH = USER_DATA_DIR / "habits.json"
ROUGH_NOTES_PATH = USER_DATA_DIR / "rough_notes.txt"

# The journal lives with the rest of the org notes, not in this project.
JOURNAL_PATH = DOOMNOTES_DIR / "journal.org"

# ── secrets/ — all gitignored ────────────────────────────────────────
# The iCal feed address, as an alternative to pasting it into
# calendar_feed.py (which is a tracked file).
ICAL_URL_PATH = SECRETS_DIR / "calendar_url.txt"
# Google ↔ Outlook sync credentials. The Google set here is read/write and
# separate from the Calendar panel's read-only ICS feed.
GOOGLE_SYNC_CREDENTIALS_PATH = SECRETS_DIR / "gcal_sync_credentials.json"
GOOGLE_SYNC_TOKEN_PATH = SECRETS_DIR / "gcal_sync_token.json"
GRAPH_APP_PATH = SECRETS_DIR / "graph_app.json"        # client_id + tenant_id
GRAPH_TOKEN_CACHE_PATH = SECRETS_DIR / "graph_token_cache.json"

# ── logs/ ────────────────────────────────────────────────────────────
SYNC_LOG_PATH = LOGS_DIR / "calendar_sync.log"
CRASH_LOG_PATH = LOGS_DIR / "dashboard_crash.log"

# ── scripts ──────────────────────────────────────────────────────────
COLLECTOR_SCRIPT = PROJECT_DIR / "collector.py"

# Everything an older, flat layout left in the project root, and where each
# one belongs now.
LEGACY_LAYOUT = {
    "cache.json": CACHE_PATH,
    "calendar_sync_status.json": SYNC_STATUS_PATH,
    "todo.json": TODO_PATH,
    "habits.json": HABITS_PATH,
    "rough_notes.txt": ROUGH_NOTES_PATH,
    "calendar_url.txt": ICAL_URL_PATH,
    "gcal_sync_credentials.json": GOOGLE_SYNC_CREDENTIALS_PATH,
    "gcal_sync_token.json": GOOGLE_SYNC_TOKEN_PATH,
    "graph_app.json": GRAPH_APP_PATH,
    "graph_token_cache.json": GRAPH_TOKEN_CACHE_PATH,
    "calendar_sync.log": SYNC_LOG_PATH,
    "dashboard_crash.log": CRASH_LOG_PATH,
    # Left behind by an atomic write that was interrupted.
    "credentials.json": SECRETS_DIR / "credentials.json",
    "token.json": SECRETS_DIR / "token.json",
}


# A write creates its scratch file and renames it over the target within
# milliseconds. One still sitting here an hour later belongs to a run that
# was killed — the collector hitting the widget's 300s timeout, the machine
# sleeping mid-write, a reboot.
TEMP_SWEEP_AGE_SECONDS = 3600


def ensure_dirs() -> None:
    for directory in MANAGED_DIRS:
        directory.mkdir(parents=True, exist_ok=True)


def sweep_temp_files(older_than_seconds=TEMP_SWEEP_AGE_SECONDS) -> list:
    """Delete orphaned atomic-write scratch files.

    Only ones old enough that no live write could still own them, so this is
    safe to run while the dashboard and the sync are going.
    """
    cutoff = time.time() - older_than_seconds
    removed = []
    for directory in (PROJECT_DIR,) + MANAGED_DIRS:
        if not directory.is_dir():
            continue
        for leftover in directory.glob("*.tmp"):
            try:
                if leftover.is_file() and leftover.stat().st_mtime < cutoff:
                    leftover.unlink()
                    removed.append(leftover)
            except OSError:
                continue        # locked or already gone
    return removed


def migrate_legacy_files() -> list:
    """Move files an older flat layout left in the project root.

    Only ever moves a file when its new home is empty, so it can't overwrite
    newer data and it's safe to call on every run.
    """
    moved = []
    for name, destination in LEGACY_LAYOUT.items():
        source = PROJECT_DIR / name
        if source.resolve() == destination.resolve():
            continue                      # already where it belongs
        if not source.is_file() or destination.exists():
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            shutil.move(str(source), str(destination))
        except OSError:
            continue                      # locked or unreadable; leave it
        moved.append((name, destination))
    return moved


def prepare() -> list:
    """Create the folders, rehome anything from the old layout, and clear out
    orphaned scratch files. Every entry point calls this before touching a
    file. Returns the moves, which are worth reporting; the swept temp files
    are garbage by definition and go quietly."""
    ensure_dirs()
    moved = migrate_legacy_files()
    sweep_temp_files()
    return moved
